<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>kinematic_planner</name>
  <version>0.1.0</version>
  <description>
    Standalone collision-free kinematic planner using sampling-based methods (RRT*, Informed RRT*).
    Supports any N-DOF robot whose links use convex collision primitives (box, cylinder, sphere). Note that this package has been designed to not have any dependency on MoveIt on purpose to expose the internals of a typical kinematic motion planner and serve as a pedagogical complement to aid in understanding the inner workings of the more robust and feature-rich MoveIt framework or other large-scale planning systems, e.g., OMPL. As a consequence, we constrain robot descriptions to be specified only in the URDF.
  </description>
  <maintainer email="me@clintonenwerem.com">Clinton Enwerem</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>shape_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>rcl_interfaces</depend>
  <depend>kinematic_planner_interfaces</depend>
  <depend>robot_3r_description</depend>
  <depend>trimesh</depend>
  <depend>ament_index_python</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
